libdrgn: python: ensure drgn.SourceLocation.__module__ is set
tests.test_docs.TestDocs.test_render is failing on Python 3.11 with:

  TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

This is coming from drgn.SourceLocation.__module__ being None (on other
Python versions, it seems to be set to "builtins"). Fix it by setting
the __name__ global when creating the SourceLocation class.

Fixes: 2f12f6346417 ("libdrgn: python: make drgn.SourceLocation actually a NamedTuple")
Signed-off-by: Omar Sandoval <osandov@osandov.com>