helpers: fix rb_find() when entry is not found
We're passing the entry type to NULL instead of the entry pointer type,
which results in errors like:

    File "/home/osandov/repos/drgn/drgn/helpers/linux/rbtree.py", line 210, in rb_find
      return NULL(root.prog_, type)
  TypeError: 'struct vm_area_struct' value must be dictionary or mapping

Signed-off-by: Omar Sandoval <osandov@osandov.com>