tests: allow test_identify_unrecognized() to pass on s390x
When testing #245, I encountered this error:

======================================================================
ERROR: test_identify_unrecognized (tests.linux_kernel.helpers.test_common.TestIdentifyAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/host/home/osandov/repos/drgn/tests/linux_kernel/helpers/test_common.py", line 57, in test_identify_unrecognized
    self.assertIsNone(identify_address(self.prog, start_addr - 1))
  File "/host/home/osandov/repos/drgn/drgn/helpers/common/memory.py", line 99, in identify_address
    symbol = prog.symbol(addr)
OverflowError: can't convert negative int to unsigned

This is because the lowest kernel address in s390x is 0, so we're
passing -1 to identify_address(). Work around that in the test.

Signed-off-by: Omar Sandoval <osandov@osandov.com>