libdrgn: dwarf_info: don't use #pragma omp master
GCC 16 gives:

  error: 'master' construct deprecated since OpenMP 5.1, use 'masked'

The GCC version in manylinux2014 (10.2.1) doesn't support masked, so
switch to using if (thread_num == 0) instead. This only resulted in
minor code layout differences.

Signed-off-by: Omar Sandoval <osandov@osandov.com>