drgndoc: use NamedTuple for {Bound,Resolved}Node to fix mypy error
Since we converted to dataclasses, we get the following error from mypy:

  error: Cannot use a covariant type variable as a parameter

The easiest fix is apparently making the type read-only.

Fixes: e404b6330c17 ("drgndoc: use dataclasses")
Signed-off-by: Omar Sandoval <osandov@osandov.com>