packit: patch RPM spec to package drgn-crash file
All of our Packit builds are failing with:

  error: Installed (but unpackaged) file(s) found:
     /usr/bin/drgn-crash

Until we cut a new release and update the spec file, we need to patch
the spec file to list the file.

Signed-off-by: Omar Sandoval <osandov@osandov.com>