libdrgn: work around Clang __muloti4 for the third time
See commit 0cb77b303c51 ("libdrgn: work around Clang __muloti4 again")
and commit 2dd14ad522a7 ("libdrgn: work around "undefined reference to
'__muloti4'" when using Clang"). These keep sneaking in because I don't
have an old enough version of Clang lying around.

Signed-off-by: Omar Sandoval <osandov@osandov.com>