contrib: ptdrgn: fix FaultError when displaying objects
Some objects (e.g. percpu variables) cannot be displayed because their
memory location is wrong, and displaying them would result in a fault
error. In the ptdrgn script, any expression resulting in such an object
will crash the entire REPL. For example:

>>> prog["cpuhp_state"]
Traceback (most recent call last):
[ ... ]
_drgn.FaultError: could not read memory from kdump: Cannot get page I/O address: PDPT table not present: p4d[0] = 0x0: 0x202a0

Handle these by simply displaying the repr() of the object:

>>> prog["cpuhp_state"]
Object(prog, 'struct cpuhp_cpu_state', address=0x202a0)
>>>

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>