libdrgn: c: don't include lookahead token in C++ identifier
cpp_append_to_identifier() consumes identifier and ":" tokens, then
consumes a template argument token if there is one. If the token that
stopped the loop isn't template arguments, it is pushed back, but the
identifier length is still computed from it. Type lookups will then
fail, e.g.:

  >>> prog.type("Foo [4]")
  LookupError: could not find 'Foo ['

Track the end of the last token that we actually consumed instead.

Fixes: 7e6efe6649c2 ("Add support for looking up types in namespaces")
Signed-off-by: Omar Sandoval <osandov@osandov.com>