pre-commit: update Black and mypy
Black 22.3.0 fixes psf/black#2964, which was breaking the CI with:

  ImportError: cannot import name '_unicodefun' from 'click'

mypy v0.942 doesn't complain about anything new.

Signed-off-by: Omar Sandoval <osandov@osandov.com>