libdrgn: object: handle memchr() return type change in C23
C23 made memchr() preserve the const qualifier of its argument, so we
now get the following error in drgn_object_read_c_string():

  error: assignment discards 'const' qualifier from pointer target type

Fix it by changing the type of the variable that we're assigning to.

Signed-off-by: Omar Sandoval <osandov@osandov.com>