drgn.helpers.linux.cgroup: fix UnboundLocalError in css_next_child()
Every once in awhile,
tests.linux_kernel.helpers.test_cgroup.TestCgroup.test_css_for_each_descendant_pre
fails with the following error from css_next_child():

  UnboundLocalError: local variable 'next_' referenced before assignment

This happens in the case that the given pos has the CSS_RELEASED flag
set and the parent doesn't have any more children.

The cause is a subtle translation error from the kernel code, where
list_for_each_entry() leaves the cursor variable set to the head, to
drgn, where an iterator like list_for_each_entry() doesn't set the loop
variable if the iterator is empty.

Fix it by explicitly returning NULL in that case.

Fixes: 820d25ae29d8 ("helpers: Add cgroup v2 helpers to traverse hierarchy")
Signed-off-by: Omar Sandoval <osandov@osandov.com>