libdrgn: debug_info: clear primitive types on main module load
When a primitive type is created prior to loading debuginfo, it gets
cached for the duration of the program's lifetime. However, a "char" may
be signed or unsigned, and drgn's choice may conflict with the one set
in the debuginfo. This can cause errors down the line, for example with
the kmodify helpers:

    TypeError: cannot convert 'char *' to incompatible type 'char *'

As a simple workaround, clear the cached primitive types when a runtime
or debug file is loaded for the main module. In the worst case, this
needlessly adds a small runtime overhead for accessing primitive types
twice: once after loading a runtime file, and once after loading a debug
file. The newly cached types will come from the debug info.

Fixes #569

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>