drgn.helpers.experimental.kmodify: use memfd_create syscall directly if not in os module
Testing a manylinux2014 wheel failed in test_kmodify with:

  AttributeError: undefined symbol: memfd_create

This is because manylinux2014 uses glibc 2.17, which doesn't have
memfd_create(). The syscall itself has been in Linux since 3.17, which
is good enough for us to use as a fallback.

Signed-off-by: Omar Sandoval <osandov@osandov.com>