Handle truncated pr_fname
It appears that some core dumps may have a "pr_fname" which isn't
nul-terminated, which leads to the following exception, even if you're
not interested in the thread name:

>>> next(prog.threads()).stack_trace()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
Exception: pr_fname is not null terminated

Handle this by creating a copy and nul-terminating it.

Closes: #483
Fixes: e6cc9b07 ("Add name to drgn.Thread")

Signed-off-by: Stephen Brennan <stephen.s.brennan@oracle.com>